language: perl

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
  - git clone https://github.com/clustericious/PlugAuth-WebUI.git /tmp/PlugAuth-WebUI
  - cd /tmp/PlugAuth-WebUI
  - dzil authordeps --missing | cpanm -n
  - dzil install --install-command 'cpanm -n .'

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

script:
  - dzil test -v

sudo: false
