---
abstract: 'Embed a web user interface into your PlugAuth server'
author:
  - 'Graham Ollis <gollis@sesda3>'
build_requires:
  File::HomeDir: 0
  File::HomeDir::Test: 0
  Path::Class::Dir: 0
  Test::Mojo: 0
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Plugin-WebUI
requires:
  PlugAuth: 0.04
  PlugAuth::Role::Plugin: 0
  PlugAuth::Role::Welcome: 0
  PlugAuth::WebUI: 0
  Role::Tiny::With: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
version: 0.03
