=head1 NAME

PlugAuth::Plugin::WebUI - Embed a web user interface into your PlugAuth server

=head1 VERSION

version 0.03

=head1 SYNOPSIS

Your PlugAuth.conf

 ---
 url: http://localhost:3000
 plugins:
  - PlugAuth::Plugin::WebUI: {}

Start L<PlugAuth>

 % plugauth daemon

and then navigate to the PlugAuth WebUI:

 http://localhost:3000/ui

=head1 DESCRIPTION

This plugin embeds the L<PlugAuth WebUI|PlugAuth::WebUI> into your PlugAuth server,
which can be accessed via the url C</ui>.

=head1 AUTHOR

Graham Ollis <gollis@sesda3>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by NASA GSFC.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

